firstname = input("Enter your First Name:")
lastname = input("Enter your Last Name:")
Age = int(input("How old are you:"))
City = input("Enter your city:")
Country = input("Enter your country:")

print(firstname)
print(lastname)
print(Age)
print(City)
print(Country)